---
title: "Reproducible Research-Peer Assessment 1"
author: "Charles Njelita"
date: "Wednesday, October 15, 2014"
output: html_document
---

## Loading and preprocessing the data
```{r, echo=TRUE}
activity <- read.csv("activity.csv", colClasses = c("numeric", "character", 
    "numeric"))
names(activity)
head(activity)
summary(activity)

```

## plots the activities:
```{r, echo=FALSE}
library(lattice)
activity$date <- as.Date(activity$date, "%Y-%m-%d")
```

## What is mean total number of steps taken per day?

```{r, echo=TRUE}
library(ggplot2)
#First is using aggregate function
StepsTotal <- aggregate(steps ~ date, data = activity, sum, na.rm = TRUE)
print(StepsTotal)
#Second we use histogram
histogram(StepsTotal$steps, main = "Total steps by day", xlab = "day", col = "green")
# Mean and Median are as follows:
mean(StepsTotal$steps)
median(StepsTotal$steps)
```

## What is the average daily activity pattern?
```{r, echo=TRUE}
time_series <- tapply(activity$steps, activity$interval, mean, na.rm = TRUE)
## We make plot
plot(row.names(time_series), time_series, type = "l", xlab = "5-min interval", 
         ylab = "Average across all Days", main = "Average number of steps taken", 
    col = "green")
```

## Imputing missing values
```{r, echo=TRUE}
activity_NA <- sum(is.na(activity))
print(activity_NA)
StepsAverage <- aggregate(steps ~ interval, data = activity, FUN = mean)
fillNA <- numeric()
for (i in 1:nrow(activity)) {
    obs <- activity[i, ]
    if (is.na(obs$steps)) {
        steps <- subset(StepsAverage, interval == obs$interval)$steps
    } else {
        steps <- obs$steps
    }
    fillNA <- c(fillNA, steps)
}

# We create a new dataset that is equal to the original dataset but with the missing data filled in.
new_activity <- activity
new_activity$steps <- fillNA

# Make a histogram of the total number of steps taken each day and Calculate and report. 
StepsTotal2 <- aggregate(steps ~ date, data = new_activity, sum, na.rm = TRUE)
hist(StepsTotal2$steps, main = "Total steps by day", xlab = "day", col = "green")

#the mean and median are as follows:
mean(StepsTotal2$steps)
median(StepsTotal2$steps)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE}
day <- weekdays(activity$date)
daylevel <- vector()
for (i in 1:nrow(activity)) {
    if (day[i] == "Saturday") {
        daylevel[i] <- "Weekend"
    } else if (day[i] == "Sunday") {
        daylevel[i] <- "Weekend"
    } else {
        daylevel[i] <- "Weekday"
    }
}
activity$daylevel <- daylevel
activity$daylevel <- factor(activity$daylevel)

stepsByDay <- aggregate(steps ~ interval + daylevel, data = activity, mean)
names(stepsByDay) <- c("interval", "daylevel", "steps")
```

```{r, echo=TRUE}
xyplot(steps ~ interval | daylevel, stepsByDay, type = "l", layout = c(1, 2), 
    xlab = "Interval", ylab = "Number of steps")
```



